### ISSUE TITLE
CodeHash for Empty Accounts

### ISSUE THREAD

**Issue by roynalnaruto** [privacy-scaling-explorations/zkevm-circuits#1101]
With respect to an [`Account`](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/state_db.rs#L41), we evaluate whether an account is empty or not by checking:
```rust
/// Return if account is empty or not.
pub fn is_empty(&self) -> bool {
    self.nonce.is_zero()
        && self.balance.is_zero()
        && self.storage.is_empty()
        && self.code_hash.eq(&CODE_HASH_ZERO)
}
```
where `CODE_HASH_ZERO` is the [Keccak256 hash of empty bytes](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/state_db.rs#L12), i.e. `0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470`.

Whereas in the RW table we populate a non-existing account by setting its code hash to `zero` (The code hash is [set to zero](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/evm/opcodes/balance.rs#L57-L65) and later this value is populated in RW table). We also [check for an empty account against a zero code hash](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/execution/balance.rs#L52-L56).

Is there a reason why we don't simply use `H256::zero()` for a non-existing account's code hash in `bus-mapping` in the first place? If not, what do you think about changing the `CODE_HASH_ZERO` to just `H256::zero()` so we stay consistent between the two crates?

**Comment by ed255** [comment]
From the EVM specification, and empty account has balance=0, nonce=0, storage=[], code=[].  From this definition, we get that the code_hash of an empty account is hash([]) = CODE_HASH_ZERO (the hash of an empty byte array).

This detail affects the value that geth returns when quering the state for a non-existing account.  In particular we see this in the `eth_getProof` method.  Here's an example of a `eth_getProof` to a non-existing account:
```
ubuntu@server:~$ curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getProof","params":["0x7F0d15C7FAae65896648C8273B6d7E43f58Fa842", [], "latest"],"id":67}' 127.0.0.1:8545 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1359  100  1240  100   119  1210k   116k --:--:-- --:--:-- --:--:-- 1327k
{
  "jsonrpc": "2.0",
  "id": 67,
  "result": {
    "address": "0x7f0d15c7faae65896648c8273b6d7e43f58fa842",
    "accountProof": [
      "0xf9015180a0ab8cdb808c8303bb61fb48e276217be9770fa83ecf3f90f2234d558885f5abf18080a01a697e814758281972fcd13bc9707dbcd2f195986b05463d7b78426508445a04a0a7c86d964ad9bf26f1c2a4db8fbc07a070625744f291bb0721a65286cc1de2b9a0bd0470637a578da1dba06031d8e55b7bb6456b14e133aae7a6e7f61b6e9f419880a02e0d86c3befd177f574a20ac63804532889077e955320c9361cd10b7cc6f580980a0e784c24cded92462d9900964d801bf176d065d5aa4a229011432204ef7f57afda065871fd31aee7e3eb3dc89050c4e54565134c5f1626e473897379cfaf98262a080a01b7779e149cadf24d4ffb77ca7e11314b8db7097e4d70b2a173493153ca2e5a0a066a7662811491b3d352e969506b420d269e8b51a224f574b3b38b3463f43f009a052ebd629dffbb5e63e4acdac48c025b3fb2b9c5c27bcb03f02916bf6077d91a980",
      "0xf8718080808080a0eec658d199ea947c3f319b8fd1ab9c497908600fa3015d09419310190c263ce380808080a00ad159e2f6c1a321105a6538b6f375cefea12e42bb00b171ebd4e8d3585f6055a0e61e567237b49c44d8f906ceea49027260b4010c10a547b38d8b131b9d3b6f848080808080"
    ],
    "balance": "0x0",
    "codeHash": "0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
    "nonce": "0x0",
    "storageHash": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "storageProof": []
  }
}
```

We're using this endpoint to populate the StateDB used in the CircuitInputBuilder with all accessed accounts (and that includes accounts which don't exist at the beginning of the block, so we're populating the StateDB with empty accounts).  This happens here: 
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/be46e7f380650a32c892b0a31b68ba5bf3948aa3/bus-mapping/src/circuit_input_builder.rs#L567-L569

Following the current implementation, we the StateDB has the same behaviour as geth, and only when we move to the RW table (and the corresponding lookups from the EVM circuit) we introduce the "encoding" of non-existing accounts as having `code_hash = 0`.

Doing the `code_hash = 0` is a bit of a hack, because that would be an invalid value for an account (because we don't know which code would give hash(code) = 0).  And it's this fact that we abuse to encode the non-existence of an account, because this case can never occur naturally.  And then we're careful to not translate this case to an MPT proof (the MPT should never contain an account with code_hash = 0), by mapping a state circuit read of a code_hash = 0, to a NonExistence account proof in the MPT.

I think that having empty accounts in the StateDB have code_hash=hash([]), and then in the bus-mapping checking for empty accounts to swap the code_hash value to 0 is useful, because it reminds us that in the circuit side, whenever we read a code_hash=0 we need to "undo" the mapping and recover the non-existence flag.

But overall I understand that this discrepancy between the StateDB and the RW Table values for code_hash can be confusing.
