### ISSUE TITLE
Should we constrain `memory_length` decomposition into 5 bytes in `MemoryAddressGadget`?

### ISSUE THREAD

**Issue by silathdiir** [privacy-scaling-explorations/zkevm-circuits#1215]
### Describe the bug

When debugging a bug and reviewing the code of [MemoryAddressGadget](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/evm_circuit/util/memory_gadget.rs#L68), I doubt if we need to save a Cell of `memory_length` and constrain it is equal to `memory_length_bytes` (type MemoryAddress) as `memory_offset`.

Or we should constrain it outside of MemoryAddressGadget. Since `construct` function only has a parameter `memory_length` of type MemoryAddress (not Cell).

```
cb.require_equal(
    "Memory length decomposition into 5 bytes",
    memory_length_bytes.expr(),
    memory_length.expr(),
);
```

What do you think? Thanks.

**Comment by han0110** [comment]
I think `MemoryAddressGadget` is originally designed to be used in successful case, so the `memory_length` is allocated as 5 bytes, which is already usable by `from_bytes::expr(&self.memory_length.cells)`.

On the other hand the `memory_offset` is allocated as a cell first and check later, it's because it's fine to have giant offset but have `memory_length = 0`, so we are not 100% sure it could be represented by 5 bytes, and that's the reason we conditionally expand it.

**Comment by silathdiir** [comment]
Got it. Thanks for quick reply. I will investigate more on error cases.
