### ISSUE TITLE
Pi Circuit: Refactor word_rlc into word lo/hi

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#1383]
Specs: https://github.com/privacy-scaling-explorations/zkevm-specs/pull/390

Blocked/Conflicted by:
- [x] https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1345

Depends on:
- https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/1388

**Comment by hero78119** [comment]
For pi circuit, originally plan is to combine keccak refactor with word lo/hi. However I thinkto fix compile/uniitest on `word-lo-hi` branch it take some efforts to debug. So we better narrow down the error scope. My idea is to review/merge replace-rlc-by-keccak spec and circuit pr  to main branch first, since it fit old design quite well, then next on word lo/hi which will make narrow down the scope of errors on `word-lo-hi` branch.

Below are plans
- [ ] review and merge pi circuit specs first: https://github.com/privacy-scaling-explorations/zkevm-specs/pull/417  -> based on word lo/hi + replace rlc by keccak 
- [ ] review and merge pi circuit https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1345 -> its not based on word lo/hi, however already replace rlc by keccak, and all unittest pass, so suggest merge it to main first.
- [ ] submit another pr to refactor pi circuit to word lo/hi with target branch `word-lo-hi` -> it took time to handle compiling errors/unittest errors in this branch. So we better narrow down error scope on word-lo-hi

@ed255 and @ChihChengLiang what do you think about the plan :) ?

**Comment by ChihChengLiang** [comment]
Hi @hero78119,
Sorry, I missed your proposal before.
We've resolved the compilation issue on `word-lo-hi` branch with #1442 and #1446.
I think it makes sense to merge https://github.com/privacy-scaling-explorations/zkevm-specs/pull/417 and  #1345 before working on this issue(#1383).

**Comment by hero78119** [comment]
> Hi @hero78119, Sorry, I missed your proposal before. We've resolved the compilation issue on `word-lo-hi` branch with #1442 and #1446. I think it makes sense to merge [privacy-scaling-explorations/zkevm-specs#417](https://github.com/privacy-scaling-explorations/zkevm-specs/pull/417) and #1345 before working on this issue(#1383).

I combined pi circuit keccak + word lo hi together, to save other reviewer times. Besides unittest passed as expected :)

**Comment by ChihChengLiang** [comment]
closed by #1345
