### ISSUE TITLE
Mismatched number of rw operations between assigned rw lookup and generated by bus-mapping

### ISSUE THREAD

**Issue by KimiWu123** [privacy-scaling-explorations/zkevm-circuits#1483]
### What command(s) is the bug in?

RUST_LOG=DEBUG RUST_BACKTRACE=1 cargo test --package zkevm-circuits --lib -- evm_circuit::execution::calldatacopy::test  --nocapture

### Describe the bug

All unit tests pass but when `RUST_LOG` is enabled, there are some errors as followings,

calldatacopy
```rust
step.rw_indices.len: 6 != assigned_rw_values.len: 6 + step.copy_rw_counter_delta: 514 in step: ExecStep { exec_state: Op(CALLDATACOPY), pc: 99, stack_size: 3, memory_size: 0, gas_left: 65527, gas_cost: 81, gas_refund: 0, call_index: 1, rwc: 112, reversible_write_counter: 0, reversible_write_counter_delta: 0, log_id: 0, bus_mapping_instance: [OperationRef{ Stack, 22 }, OperationRef{ Stack, 23 }, OperationRef{ Stack, 24 }, OperationRef{ CallContext, 48 }, OperationRef{ CallContext, 49 }, OperationRef{ CallContext, 50 }], copy_rw_counter_delta: 514, error: None }
```

codecopy
```rust
step.rw_indices.len: 3 != assigned_rw_values.len: 3 + step.copy_rw_counter_delta: 48 in step: ExecStep { exec_state: Op(CODECOPY), pc: 99, stack_size: 3, memory_size: 0, gas_left: 978991, gas_cost: 18, gas_refund: 0, call_index: 0, rwc: 27, reversible_write_counter: 0, reversible_write_counter_delta: 0, log_id: 0, bus_mapping_instance: [OperationRef{ Stack, 3 }, OperationRef{ Stack, 4 }, OperationRef{ Stack, 5 }], copy_rw_counter_delta: 48, error: None }
```

extcodecopy
```rust
step.rw_indices.len: 9 != assigned_rw_values.len: 9 + step.copy_rw_counter_delta: 54 in step: ExecStep { exec_state: Op(EXTCODECOPY), pc: 120, stack_size: 4, memory_size: 0, gas_left: 978988, gas_cost: 2612, gas_refund: 0, call_index: 0, rwc: 28, reversible_write_counter: 0, reversible_write_counter_delta: 1, log_id: 0, bus_mapping_instance: [OperationRef{ Stack, 4 }, OperationRef{ Stack, 5 }, OperationRef{ Stack, 6 }, OperationRef{ Stack, 7 }, OperationRef{ CallContext, 17 }, OperationRef{ CallContext, 18 }, OperationRef{ CallContext, 19 }, OperationRef{ TxAccessListAccount, 3 }, OperationRef{ Account, 3 }], copy_rw_counter_delta: 54, error: None }
```

returndatacopy
```rust
tep.rw_indices.len: 6 != assigned_rw_values.len: 6 + step.copy_rw_counter_delta: 4 in step: ExecStep { exec_state: Op(RETURNDATACOPY), pc: 398, stack_size: 4, memory_size: 32, gas_left: 976340, gas_cost: 6, gas_refund: 0, call_index: 0, rwc: 167, reversible_write_counter: 1, reversible_write_counter_delta: 0, log_id: 0, bus_mapping_instance: [OperationRef{ Stack, 30 }, OperationRef{ Stack, 31 }, OperationRef{ Stack, 32 }, OperationRef{ CallContext, 63 }, OperationRef{ CallContext, 64 }, OperationRef{ CallContext, 65 }], copy_rw_counter_delta: 4, error: None }
```

All the failures are because the number of rw operations is inconsistent between generated by bus-mapping and assigned by EVM circuit. From the error message, it's due to the rw operations in copy table lookup is not included and happens when `dst_tag` is `Memory`.

### Concrete steps to reproduce the bug. If it's able reproduce via testool, please share `test_id` from jenkins report

na

**Comment by hero78119** [comment]
Quick check, and seems it's because e.g. in [codecopy.rs](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/evm/opcodes/codecopy.rs#L91) 
```rust
let mut exec_step = state.new_step(geth_step)?;
```
is called second time, without reusing the same `exec_step` create earlier.  It makes the memory rw event populated by copy are put into another `bus_mapping_instance` vector, then later it was discard therefore make the rw mismatch.  Same thing happend on [extcodecopy](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/evm/opcodes/extcodecopy.rs#L147)/[returndatacopy](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/evm/opcodes/returndatacopy.rs#L140)/[codedatacopy](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/evm/opcodes/calldatacopy.rs#L120)

In [create.rs](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/bus-mapping/src/evm/opcodes/create.rs#LL23C17-L23C26) it's reused therefore no such problem.
