### ISSUE TITLE
Support invalid tx

### ISSUE THREAD

**Issue by KimiWu123** [privacy-scaling-explorations/zkevm-circuits#1611]
### Describe the feature you would like

A follow-up issue of #1503 

----

### Description
Support skipping the following invalid transactions:
- nonce too low
- nonce too high
- intrinsic gas too low
- insufficient funds for gas * price + value

related issue: https://github.com/taikoxyz/zkevm-circuits/issues/70

### Contents
- Check if a TX is invalid by adding a few auxiliary columns to the TX table.
- The related PR in [zkevm-specs](https://github.com/privacy-scaling-explorations/zkevm-specs) is https://github.com/privacy-scaling-explorations/zkevm-specs/pull/338

**Comment by ed255** [comment]
@xiaodino would you like to get this task assigned to you?

**Comment by CeciliaZ030** [comment]
> @xiaodino would you like to get this task assigned to you?

Hi @ed255, I'm currently doing this :) 
@xiaodino has been working on taiko's bridge these days, we reverted his PR from our end and here's a new draft PR https://github.com/taikoxyz/zkevm-circuits/pull/157
Also I ended up adding a new `ExecStep` rather than error state since invalid Tx shouldn't even make it to execution, and hence shouldn't be thrown in error. A separate state that skips them seems more neat I guess.
