### ISSUE TITLE
[keccak] Optimize permutation circuit

### ISSUE THREAD

**Issue by CPerezz** [privacy-scaling-explorations/zkevm-circuits#489]
After we discussed with the team about the permutation circuit layout. We knew that something was not entirely correct.
Seeing the 2-phase Layouter result on the printed circuit left us thinking that there had to be a way to optimize the permutation circuit more.

This are the current numbers we get for the permutation circuit:
```
Num advice columns: 410
Num fixed columns: 203
Num instance columns: 2
Num lookups: 102
Num gates: 163
num polys: 278
max_degree_poly: 6 
max_degree_lookup_input: 3 - lookup input 'Lookup i/o_coeff at Base conversion table'
max_degree_lookup: 1 - lookup table 'b13 -> b9 table'
```

The ideas are:
- [x] As @therealyingtong mentioned, collapse the advice column generation into the global circuit (no sub-circuits should create advice columns, they should be passed over). https://github.com/appliedzkp/zkevm-circuits/pull/501
- [ ] As discussed and agreed with @Brechtpd, create a Tag and collapse all the lookup tables into a single one (Single shuffle argument). https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/569
- [ ] There's still the need to address #275 and reduce the columns passed to the Iota gates.

**Comment by Brechtpd** [comment]
Getting the degree down of the custom constraints to `5`, and of the lookup table inputs to `2` will probably also be worth it (at the cost of some extra columns so certainly a balance to be made there) to get the extended domain to x4 instead of the current x8.

I am thinking of some other possibilities as well but I still have to look into things more to see if they can work.

**Comment by CPerezz** [comment]
Are you working in any specific task for these? I'll add them to the issue as tasks.

I'm working on collapsing `Advice` columns first so that the rest is easier to follow.

**Comment by Brechtpd** [comment]
Currently `2*a + b + 3*c` is used to pack the data to calculate `a ^ (~b & c)` which packs the data in [0..6]. However I found that also using subtraction (and making sure underflows/overflows are impossible) of the different inputs often results in a tighter packing. For example `a ^ (~b & c)` can also be packed using `[3]*64 + b - 2*a - c` which packs the data in [0..4] (`[0, 1, 1, 0, 0]` is the map to get the boolean result), allowing more bits to get packed in a single lookup for similar lookup table lengths.

**Comment by Brechtpd** [comment]
For `a ^ (~b & c) ^ d` it's `pack([5]*64) + c - 2*a - b - 2*d` which packs it into [0..6]. The boolean result is found with the mapping `[0, 0, 1, 1, 0, 0, 1]`. I gave the result for `a ^ (~b & c)` because I think that one can primarily be used most of the time so maybe more important eventually but yeah in the current code the version with the extra XOR is used.

With `[3]*64` and `[5]*64` I just mean the coefficient `3` or `5` packed as the representation for all 64 bits (maybe rust syntax like `[3; 64]` would have made more sense but for some reason I used python syntax). This value is only added so the coefficients in the packed representation remain in the [0..6] range at all time.

**Comment by ChihChengLiang** [comment]
So the original base conversion from 9 [0..8], now packs into base 7 [0..6]. Assuming 2^16 rows, we can still only look up 5 chunks at a time. 
`16/ log2(9) =  5.04`
`16/log2(7) = 5.7`
Assuming we can improve to 6 chunks, we can reduce the lookup and the running sums from 13 rows to 11 rows.
`64/5 = 12.8 ~= 13`
`64/6 = 10.6666 ~= 11`
Assuming we stack everything together and use minimal gates in #541 style. That saves 2 rows for lookup, input running sum, and output running sum, respectively. Total saving is 3.6k for a keccak_f.
`(2+ 2+ 2) * (25 lanes) * (24 rounds) = 3600 rows`

**Comment by CPerezz** [comment]
@ChihChengLiang let's benchmark once you have that as I'm curious on how the 9 col lookup will perform (also count the range, bool and special chunks checks).

**Comment by ChihChengLiang** [comment]
I think this is outdated as we now use implementations from #634
