### ISSUE TITLE
state lexicographic ordering can overlap for `tag` 

### ISSUE THREAD

**Issue by DreamWuGit** [privacy-scaling-explorations/zkevm-circuits#520]
code line in https://github.com/appliedzkp/zkevm-circuits/blob/main/zkevm-circuits/src/state_circuit/lexicographic_ordering.rs#L322 
`    be_bytes[0] = row.field_tag().unwrap_or_default() as u8 + ((row.tag() as u8) << 4);
`. 

For `RwTableTag::CallContext ` ,  its corresponding field tag `CallContextFieldTag` consists of more than 20 items.   when current row is `CallContext` tag,  next row is tag behind `RwTableTag::CallContext `, like `TxLog`,  it is maybe not distinguishable to use `be_bytes[0]`. 
i.e.     
- current row is `CallContext`  with `CallContextFieldTag::CodeSource` ,      
   be_bytes[0] = 20 + 10 <<4  = 180. 
- next row is `TxLog`  with `TxLogFieldTag::Address` ,    
   be_bytes[0] = 1 + 11 <<4  =  177.   

after `RW` sort , it breaks next row value should be bigger than current row.

**Comment by z2trillion** [comment]
https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/523 will fixes the TODO. 4 bits for the field tag was previously enough because none of the tests used larger field tags, but https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/476 does, so we had to fix this issue now.

**Comment by DreamWuGit** [comment]
closing as #523 merged!
