### ISSUE TITLE
Possible code optimisation

### ISSUE THREAD

**Issue by web3moon** [privacy-scaling-explorations/zkevm-circuits#536]
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/ad66311c57680189cf9504012711078d31050f77/zkevm-circuits/src/evm_circuit/util.rs#L259-L264

If a suitable column is found, should the for loop be broken here ?

**Comment by Brechtpd** [comment]
The goal that we try to achieve here is for an opcode to use the fewest amount of rows as possible. And so what the code here does is to try and find a cell location in a suitable column that currently has the smallest height (the column that currently has the fewest amount of cells used already). Breaking up the for loop as soon as any suitable column would be found would just put all cells in the first suitable column until it's completely filled up, which makes it so the opcode uses as many rows as possible instead of spreading the work over the multiple available columns as much as possible.

You could argue that, to optimize the performance of the building of the circuit (which isn't really important, the prover performance is the important one), the current "best" position could be stored somewhere and get updated more smartly so we don't always have to search all the columns, but there aren't that many columns for this to really make a difference so this easy and naive solution works fine I think (at least for now).
