### ISSUE TITLE
Cargo.lock: halo2_proofs points to the wrong commit

### ISSUE THREAD

**Issue by pinkiebell** [privacy-scaling-explorations/zkevm-circuits#549]
Across the projects we reference
`halo2_proofs = { git = "https://github.com/appliedzkp/halo2.git", tag = "v2022_05_09" }`
and inside Cargo.lock it points to `tag=v2022_05_09#9992785dca35926ded74f6ec7c8dfbac507317d0`
however `v2022_05_09` is `bffb83e4d18fe81f4b998c79f9831bd380e1a961` and `9992785dca35926ded74f6ec7c8dfbac507317d0` is actually `v2022_05_06`.

depends-on: https://github.com/privacy-scaling-explorations/halo2wrong/pull/29

**Comment by CPerezz** [comment]
I think the issue is that `halo2_wrong` depends on `halo2` `circuit` branch instead of the tag. Which might cause issues when it comes to Cargo as the Resolver2 is not set.

**Comment by ed255** [comment]
> I think the issue is that `halo2_wrong` depends on `halo2` `circuit` branch instead of the tag. Which might cause issues when it comes to Cargo as the Resolver2 is not set.
I think no matter if `halo2_wrong` depends on tag or commit id, we'll always have the problem that `halo2_wrong` and `zkevm_circuits` must match on their dependency version of halo2.  And I think this will happen until we publish versions of our halo2 fork (so that semver rules apply), but I think we're still in an early stage to do that.
So I think the current solution is just bump the `halo2` dependency in `halo2wrong`.
