### ISSUE TITLE
Implement EndBlock execution state

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#575]
Currently we have an EndBlock gadget that is dummy (it doesn't have any constraints).

The EndBlock state was specified here https://github.com/privacy-scaling-explorations/zkevm-specs/pull/88 , nevertheless there are a few details that may be missing from the spec:
```python
# TODO: Introduce constrain_instance to constrain the equality between witness
#       and public input, for total_tx and total_rw
```
- Constraint that the number of tx processed in the EVM is the same as the number of txs in the tx table
- Constraint that the number of ops in the rw_table from the State circuit match the number of ops "emitted" from the EVM circuit.

Dependency:

- [x] [#711](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/711)

**Comment by han0110** [comment]
Since currently we have variable step height for each `ExecutionState`, using `EndBlock` to pad all remaining rows might not always work because it's not single row, it could possibly go into blinding factors regions (zk) or wrap around (non-zk) and break some constraint.

One approach to make it `EndBlock` single row (and repeating `EndBlock` until last enabled `q_step`) is to turn off zk and gain one extra degree to make `ExecutionState` selectors fewer, and at the same time not make the circuit wider.

Another very naive approach that just comes to my mind is to introduce a new fixed column `global_offset`, which is filled with the index of row it's is in (as <code>0..2<sup>k</sup> - 1</code>), and in `EndBlock` we constrain the next row's `num_rows_until_next_step` to be <code>2<sup>k</sup> - (1 + global_offset)</code> (might need to minus `blinding_factors()` if zk), and `q_step` will never be `1` again.

Also it seems we don't need to share public input anymore (so no need of `constrain_instance`) thanks to the idea introduced by @ z2trillion in https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/558 (for checking number of tx, we might be able to also adapt the same trick).

**Comment by aguzmant103** [comment]
Sub-tasks:
[] [#711](https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/711)

**Comment by aguzmant103** [comment]
Still in progress, missing one review.
