### ISSUE TITLE
bug: value_assignment of Rw::Account Nonce is inconsistent

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#592]
in witness.rs, it is RLCed, https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/6e49a1ad71692f532f1de461083e0926804b0f1b/zkevm-circuits/src/evm_circuit/witness.rs#L830

but in begin_tx, it is not RLCed, https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/6e49a1ad71692f532f1de461083e0926804b0f1b/zkevm-circuits/src/evm_circuit/execution/begin_tx.rs#L80 and https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/6e49a1ad71692f532f1de461083e0926804b0f1b/bus-mapping/src/evm/opcodes.rs#L275 

So i guess if we counter nonce bigger >=256, circuit will encounter error?

value_prev also has this problem

**Comment by han0110** [comment]
I thought nonce is already defined to be u64 in yellowpaper, so it could be just represented as raw value instead of RLCed. But for witness assignment it's updated to use RLCed value in #462 ([ref](https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/462/files#diff-09bf944a4f9216c1053a271fea0ff2f7a985380789b990f8e4ac530159214df2)), is this change intended @z2trillion?

**Comment by z2trillion** [comment]
It wasn't intentional. Made a PR for fix this.

https://eips.ethereum.org/EIPS/eip-2681 made ths change to u64's for nonces.
