### ISSUE TITLE
State circuit - MPT circuit integration

### ISSUE THREAD

**Issue by miha-stopar** [privacy-scaling-explorations/zkevm-circuits#607]
Besides lookups that are enabled in the MPT, I think there are two other things need to be considered.

1. Address // Key

Address or key gets hashed before it’s inserted into the trie. So the position of the node in the trie is determined by the hashed value.

For example, let the address be `B0 … B31`. Let’s say:
`hash(B0 … B31) = b0 … b31`

If the node is stored in the second level, we split `b0` into nibbles: `b0 = n1 * 16 + n2`, the position
of the node in the first branch is `n1`, the position of the node in the second level is `n2`.

MPT circuit checks the node is stored at the proper position, so it needs the values `b0 … b31` (and not `B0 … B31`).

The address RLC that is used for MPT lookup thus needs to be `b0 + b1*r + … + b31*r^31`. That means
state circuit needs to verify `hash(B0 … B31) = b0 … b31` using Keccak lookup and then use `b0 + b1*r + … + b31*r^31` for MPT lookup.

2. Randomness for RLC

When the randomness `r` is computed, the commitments to the MPT advice columns need to be in the transcript because MPT advice columns contain data that we didn’t commit to in other circuits. Implicitly we committed to all the data that determines the getProof data (determined by address/key and value), but it feels like if the randomness `r` does not depend directly on getProof data it’s possible to do the following for example: we have a branch `b0 … b140` and we should check `keccak_lookup(b0 + … b140*r^140, hash(branch))`, but we can try to find another stream of bytes `a0 … a140` such that `b0 + … b140*r^140 = a0 + … a140*r^140`, because we didn’t commit explicitly to `b0 … b140` and pushed this commitment into the transcript. But I haven’t followed the discussion about randomness too closely so maybe these kind of things have already been discussed.

Any thoughts on these two points?

**Comment by z2trillion** [comment]
What lookups are enabled in the MPT circuit at the moment?

Regarding 1:
The MPT lookups the state circuit does from https://github.com/privacy-scaling-explorations/zkevm-specs/issues/217#issuecomment-1170338113 look like
```
MptAccountStorageLookup {address, key, commited_value, value,  old_root, new_root}
```
and 
```
MptAccountLookup {address, field_tag, commited_value, value,  old_root, new_root}
```
Are you proposing that instead they should look
```
MptAccountStorageLookup {keccak(address), keccak(key), commited_value, value,  old_root, new_root}
```
and 
```
MptAccountLookup {keccak(address), field_tag, commited_value, value,  old_root, new_root}
```
?
I don't think it makes sense to add keccak lookups to the state circuit for this, especially when the mpt circuit is already doing a lot of other keccak lookups?

**Comment by miha-stopar** [comment]
Exactly. Yes, it makes sense to make this check in the MPT circuit.

**Comment by ed255** [comment]
I agree with @z2trillion on point 1: Currently the state circuit is not doing any keccak lookups; and it would be good if we don't need to introduce a new inter-circuit dependency.  Since the MPT already does keccak lookups, maybe the MPT can receive the unhashed address and unhashed RLC(key), and do the hashing itself?

About point 2: I see your point about what a malicious prover can do if the transcript used to derive `r` doesn't contain `b0 … b140`.  But I think that's not a problem, we just need to make sure that the columns holding `b0 … b140` are committed in phase 1 and belong to the global transcript used to derive `r`.  I think that in general, all columns that are used directly (eg: `col * r  + ... = 0`) or indirectly (eg: `col - aux = 0; aux * r + ... = 0`) in expressions that do RLC need to be committed in phase 1.

**Comment by z2trillion** [comment]
I made a draft pr that adds (faked) mpt update lookups to the state circuit: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/621/files#diff-3c34e18842d60643d37a4c79494077f57237418db3eb5b2539827baa23859d60R484

The biggest issue with it is the format of the lookups from the state circuit into the mpt circuit. https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/621/files#diff-3c34e18842d60643d37a4c79494077f57237418db3eb5b2539827baa23859d60R480. That function RLC's some values which are already RLC'ed, which I'm pretty sure is not sound. @icemelon and I were thinking about adding another randomness `r_2` for the case of nested RLC's. Does this have any relation to point 2 here?

**Comment by ed255** [comment]
> The biggest issue with it is the format of the lookups from the state circuit into the mpt circuit. https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/621/files#diff-3c34e18842d60643d37a4c79494077f57237418db3eb5b2539827baa23859d60R480. That function RLC's some values which are already RLC'ed, which I'm pretty sure is not sound. @icemelon and I were thinking about adding another randomness `r_2` for the case of nested RLC's. Does this have any relation to point 2 here?

I also have the impression that doing RLC of values that are already RLC'ed (where both RLCs use the same randomness) is unsafe because it may allow the prover to swap values.  For example, if we have:
```
p1(x) = a + r * b + r^2 * c
p2(x) = d + r * e
p3(x) = p1 + r * p2 = a + r * b + r^2 * c + r * d + r^2 * e =  a + r * (b+d) + r^2 * (c+e) 
// p3(x) has RLC of RLC.  The prover can play around with (b, d) and (c, e) as long 
// as the addition of the elements in the pairs remain equal, and the RLC result will be the same.
``` 

I think using a second randomness as you suggest is a possible solution.  I think this randomness should be derived from a transcript that includes the commitments to the first layer RLC'ed values.  I think the challenge API that @han0110 has prepared supports querying for a randomness at multiple phases, but maybe he can confirm this!

Another option that comes to my mind is to shape the second RLC so that it's equivalent to the RLC of the raw inputs, and no to values land with the same power of randomness.  For example, following the previous example:
```
p3(x) = p1 + r^3 * p2 = a + r * b + r^2 * c + r^3 * d + r^4 * e
```
