### ISSUE TITLE
Failing `CALL` when sending value

### ISSUE THREAD

**Issue by adria0** [privacy-scaling-explorations/zkevm-circuits#636]
`test_with_value` fails 

```
---- testme::test::test_with_value stdout ----
thread 'testme::test::test_with_value' panicked at 'should work: [ConstraintNotSatisfied { constraint: Constraint { gate: Gate { index: 44, name: "CALL" }, index: 114, name: "numerator - remainder == quotient ⋅ denominator" }, location: InRegion { region: Region { index: 6, name: "Execution step" }, offset: 73 }, cell_values: [(VirtualCell { name: "", column: Column { column_type: Advice, index: 23 }, rotation: 0 }, "1")] }, ConstraintNotSatisfied { constraint: Constraint { gate: Gate { index: 44, name: "CALL" }, index: 116, name: "lhs - rhs == diff - (lt ⋅ range)" }, location: InRegion { region: Region { index: 6, name: "Execution step" }, offset: 73 }, cell_values: [(VirtualCell { name: "", column: Column { column_type: Advice, index: 23 }, rotation: 0 }, "1")] }]', evm-testvectors/src/testme.rs:65:56
```
when `test_without_value` works for the following code:

```
    use eth_types::geth_types::GethData;
    use eth_types::{address, bytecode, Word};
    use mock::TestContext;
    use zkevm_circuits::evm_circuit::witness::block_convert;
    use zkevm_circuits::evm_circuit::test::run_test_circuit_incomplete_fixed_table;

    #[test]
    fn test_with_value() {
        test(Word::one());
    }

    #[test]
    fn test_without_value() {
        test(Word::zero());
    }

    fn test(value: Word) {
        let addr0 = address!("0x00000000000000000000000000000000000cafe0");
        let addr1 = address!("0x00000000000000000000000000000000000cafe1");
        let addr2 = address!("0x00000000000000000000000000000000000cafe2");

        let code1 = bytecode! {
            PUSH32(0)
            PUSH32(0)
            PUSH32(0)
            PUSH32(0)
            PUSH32(value)
            PUSH20(0xcafe2)
            PUSH32(100000)
            CALL
            STOP
        };
        let code2 = bytecode! {
            STOP
        };

        let block : GethData = TestContext::<3, 1>::new(
            None,
            |accs| {
                accs[0]
                    .address(addr0)
                    .balance(Word::from(1u64 << 30));
                accs[1].address(addr1).code(code1);
                accs[2].address(addr2).code(code2);
            },
            |mut txs, accs| {
                txs[0].from(accs[0].address).to(accs[1].address)
                .gas(Word::from(200000u64)).value(Word::one());
            },
            |block, _tx| block.number(0xcafeu64),
        )
        .unwrap()
        .into();
        let block_data = bus_mapping::mock::BlockData::new_from_geth_data(block);
        let mut builder = block_data.new_circuit_input_builder();
        builder
            .handle_block(&block_data.eth_block, &block_data.geth_traces)
            .unwrap();
        let block = block_convert(&builder.block, &builder.code_db);
        run_test_circuit_incomplete_fixed_table(block).expect("should work")
    }
```

note: this has been detected by running the `InternlCallStoreClearsSuccesFiller.json` test

**Comment by han0110** [comment]
Thanks for reporting the issue with reproducible code, it's really convenient for me to do trouble shooting!

It takes me some time to realize the issue, so in [`InternlCallStoreClearsSuccesFiller.json` ](https://github.com/ethereum/tests/blob/27721a74131ccb6e2fa99b8a76740849d3d13fc7/GeneralStateTests/stTransactionTest/InternlCallStoreClearsSucces.json) we can find that account `0x000...000` has `code = "0x600060..."` but with `nonce = 0`, which is identified as non-empty account by `geth` like [this](https://github.com/ethereum/go-ethereum/blob/14b0eedacf8e7d3cdcfbc82a616810337a7f16ca/core/state/state_object.go#L97-L99).

However, since [EIP-161](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-161.md), every deployed contract will have `nonce` starts as `1`, which means we can save the check if `code` is empty or not, and that's also how currently `CALL` is implemented, so we have this issue.

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/4bdb2a2e70b6137ec0905bede725f5750fe4caf7/zkevm-circuits/src/evm_circuit/execution/call.rs#L175-L181

One solution to resolve this issue is to add such redundant check for such customized genesis setting (some accounts have codes without nonce) just like how `EXTCODEHASH` is implemented:

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/4bdb2a2e70b6137ec0905bede725f5750fe4caf7/zkevm-circuits/src/evm_circuit/execution/extcodehash.rs#L83-L90

Will try this to see if it works and submit a PR later.
