### ISSUE TITLE
Use a non-random "randomness" value for testing

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#641]
Currently we are using a different random value on each test run for the randomness used for the RLC in the circuits:
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/46dd697dbf855b252e50b08543ac0f9eb4bc4010/zkevm-circuits/src/evm_circuit/witness.rs#L1361

I believe it's better for tests to use always the same "random" value to get reproducible executions and run the test always with the same intermediate values.  Even more, we can use a particular value that makes debugging an RLC encode value easier, like `0x1000` as suggested by @lispc .

See https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/622#issuecomment-1196355757 for a discussion on this topic.

**Comment by CPerezz** [comment]
I would suggest to use `SeededableRng`. See: [SeedableRng](https://docs.rs/rand/latest/rand/trait.SeedableRng.html#)

**Comment by CPerezz** [comment]
Well I was working on this but makes sense to use a fixed randomness value as basically it's for debugging purposes. And also, we don't have any Rng traits associated anywhere. So we're much more free in that regard. 

Aside from that, even using in `0x1000` can be a solution now, we should keep an eye on this so that we have a solution that can scale with the codebase.

**Comment by CPerezz** [comment]
I think we can close this and open a new issue regarding the implementation of a global randomness solution for our testing.

**Comment by CPerezz** [comment]
Closing this in favour of #684
