### ISSUE TITLE
Lookup table addition to keccak circuit

### ISSUE THREAD

**Issue by aguzmant103** [privacy-scaling-explorations/zkevm-circuits#712]
Depends on #692

**Comment by ChihChengLiang** [comment]
@CPerezz Can you give some clarification for this task? IIUC, we want to complete the following listed items.

- Enshrine one of the keccak circuits, specifically `KeccakBitConfig`.
- Currently,...
  - SuperCircuit has keccak_inputs built from the Circuit Input Builder.
  - SuperCircuit then use `keccak_table.load()` to load KeccakTable with all keccak_inputs.
  - We want to replace `keccak_table.load()` with `KeccakBitConfig.generate_witness`. So that we not only load the table but also assign the keccak circuit.

Does that make sense to you?

**Comment by CPerezz** [comment]
This issue exists due to the fact that we wanted to split the Keccak Circuit impl task into smaller ones. 

1. We have #692 which will connect the permutations between themseleves.
2. We have this issue which will include a lookup table which will be loaded with the circuit inputs.
3. Any Supercircuit stuff comes after 1 and 2.

**Comment by ChihChengLiang** [comment]
It looks like we already have the lookup table loading logic in two places

1. This one is in keccak circuit https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/d16ac9b8bda39c45c82a41d2d59054c85abbc9a1/zkevm-circuits/src/keccak_circuit/keccak_bit.rs#L648
2. This one is in the super circuit https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/38aca326857287a9e7a2d75033a0f7d8af1252d2/zkevm-circuits/src/table.rs#L652

**Comment by CPerezz** [comment]
Ohh you're right! I wonder how this is possible if the permutations aren't connected entirely AFAIK.

**Comment by ChihChengLiang** [comment]
So they are not connected. I can connect them together. Let me create a demo PR.

**Comment by ChihChengLiang** [comment]
closed by #717
