### ISSUE TITLE
Easy to use EVM simulator for unit tests

### ISSUE THREAD

**Issue by Brechtpd** [privacy-scaling-explorations/zkevm-circuits#77]
Currently the way to write unit tests is to manually create the execution steps and resulting operations for all the different op codes each time. This is very tedious. It would be great if we could have a very simple EVM simulator (which would also be updated when implementing an opcode) where we could just write something like this (with maybe some extra ways to mock data for testing purposes):

```
evm.push(1);
evm.push(2);
evm.add();

try_test_circuit!(
   evm.get_execution_steps(),
   evm.get_operations(),
    Ok(())
);
```

I think this will make writing unit tests much more pleasant and faster.

The closest thing to this may be something @CPerezz is working on. Do you think there could be some overlap here @CPerezz? If not I'd be willing to do this myself.

**Comment by CPerezz** [comment]
I completely agree. This would be a huge improvement to the test suite.

For now, the focus is to finish a first `bus-mapping` then work on the circuits and finally, improve everything we can.

But we're happy to recieve any contributions regarding this. The only difficult thing I see is that the traces we use in the tests are obtained here: https://github.com/appliedzkp/zkevm-testing-vectors and they require `geth` output. If you can emulate it and obtain the same traces and embedd that in a macro or similar, we will be happy to accept it!

**Comment by mask-pp** [comment]
I am also doing evm testing related transformation work, hoping to participate in improving the experience together！

**Comment by Brechtpd** [comment]
Have created a draft PR with how it could work: #91

The fact that the evm circuit uses very different `ExecutionStep`s and `Operation`s than the ones in the busmapping was an unexpected blocker to really make it work very well for now without many temporary hacks. What is the current plan for that @CPerezz? Perhaps I can help with the refactoring for that once you think it's ready to do so.

**Comment by CPerezz** [comment]
First of all, thanks a lot for the work and efforts @Brechtpd !! :smile: 

I've taken a look to the PR. And as said looks like a really nice idea. I'll leave there some comments and hints regarding the code and the direction is taking.

As for the integration of this kind of developer tooling, this is the current status:

- We are still finalizing the `bus-mapping` crate, through refactors so that we can have a better integration with the circuits crate.
- We need to add all of the `StorageOp`s and Storage opcodes logic in the `bus-mapping` crate and design a solution that is able to query the Geth node to get Merkle proofs, and any other info needed.
- We need to start querying also the node regarding all of the fields that we need to add into each `ExecutionStep`. See: https://github.com/appliedzkp/zkevm-circuits/blob/ab0b56ca75fdc936ed438b25354a3a08f7b14412/zkevm-circuits/src/evm_circuit.rs#L22
- Once all of the previous things are done, we can then start working towards a better integration.


Therefore, that means that there's still quite a lot of work to do.  Will suggest in the PR a way we can take that would allow to integrate this and not be blocked on the meantime.

We're going to be working during the next week or two on a solution to provide a much better integration with Go using RPC or something similar so that bus-mapping can query the node for extra info that is not provided by the traces or something along these lines.

My suggestion would be to wait until this work is done and we have a clear path for that. And on the meantime, I'll write in the PR how do I foresee this being merged and useful and working earlier.
