### ISSUE TITLE
Unnecessary to check `IsPersistent` in the end of a call

### ISSUE THREAD

**Issue by han0110** [privacy-scaling-explorations/zkevm-circuits#815]
We only need to check `IsSuccess` to in the end of a call, since `IsPersistent`'s value is always derived from `IsSuccess` and caller's `IsPersistent`, and the root `IsPersistent` is just `IsSuccess`.

Currently `STOP` or other implemented errors could be improved to remove this unnecessary check.

**Comment by ed255** [comment]
> We only need to check `IsSuccess` to in the end of a call, since `IsPersistent`'s value is always derived from `IsSuccess` and caller's `IsPersistent`, and the root `IsPersistent` is just `IsSuccess`.

The `IsPersistent` derivation you mention is this one right?
https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/f0a83024820923fedb3371c55f164470c844d29b/zkevm-circuits/src/evm_circuit/execution/call.rs#L137-L142

**Comment by han0110** [comment]
Yes, and this in `BeginTx`:

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/f0a83024820923fedb3371c55f164470c844d29b/zkevm-circuits/src/evm_circuit/execution/begin_tx.rs#L60-L65

**Comment by DreamWuGit** [comment]
I agree, will update Stop & Error gadget !

**Comment by ChihChengLiang** [comment]
Let me try to give a quick summary of this issue, after talking to @han0110.

Here's the `call` diagram from the [zkevm-docs](https://privacy-scaling-explorations.github.io/zkevm-docs/design/reversible-write-reversion2.html). A parent call can invoke a child call, and when the child call is completed we go back to the parent call.
![](https://privacy-scaling-explorations.github.io/zkevm-docs/design/state-write-reversion2_call-depth.png)

When a call fails, we need to revert all the state changes and restore the state before the failing call. To solve this specific problem, we define two boolean statuses to determine whether we should revert the state:

- `IsSuccess`: means if the current call will succeed or not.
- `IsPersistent`: tracks if we are coming from an ancestor that's failing.
   -  If all our ancestors are all successful then this value is true. The EVM keeps all the state changes until now.
   -  But if one or more than one of our ancestors fails, then this value is false. The EVM keeps the state changes up to the call before the earliest failing ancestor.

So is the current call persistent? This is equivalent to asking "is the current call successful?" and "is the parent persistent?." We have enforced this check at the beginning of the transaction and the beginning of the call.

https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/c798befbc27086141e2617dfc9a36cb02ba5a4ed/zkevm-circuits/src/evm_circuit/execution/callop.rs#L147

Since the check is already enforced,  when we exit a call or a transaction, i.e. ending the computation with STOP or all kinds of error, we no longer have to check the `IsPersistent` again.
