### ISSUE TITLE
Refactor Copy Circuit with challenge API

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#955]
Reference example: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/803

**Comment by CPerezz** [comment]
AS this is marked with `Good First Issue`. I think it's also nice to put here which are the steps expected to be taken to do this migration:
1. Identify all of the Advice Columns of the circuit that will have randomness-related values assigned inside.
2. Replace the creation of these Columns at configure time using `meta.advice_column_at(PHASEX);`
3. Force the `configure` and witness assignment methods to recieve as fn parameter `Challenges<Value/Expression<F>>`
4. Use the challenges instead of the randomness in all the places.

Also, to take into account!
1. `evm_word` challenge should be after FirstPhase.
2. `keccak_input` is not required for any circuit that isn't keccak itself.
3. Compressed lookup input (should be after SecondPhase since it contains some non-linear-combination of RLC values in SecondPhase, for instance inverse of EVM word).
