### ISSUE TITLE
Refactor Exp Circuit with challenge API

### ISSUE THREAD

**Issue by ed255** [privacy-scaling-explorations/zkevm-circuits#956]
Reference example: https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/803

**Comment by CPerezz** [comment]
AS this is marked with `Good First Issue`. I think it's also nice to put here which are the steps expected to be taken to do this migration:
1. Identify all of the Advice Columns of the circuit that will have randomness-related values assigned inside.
2. Replace the creation of these Columns at configure time using `meta.advice_column_at(PHASEX);`
3. Force the `configure` and witness assignment methods to recieve as fn parameter `Challenges<Value/Expression<F>>`
4. Use the challenges instead of the randomness in all the places.

Also, to take into account!
1. `evm_word` challenge should be after FirstPhase.
2. `keccak_input` is not required for any circuit that isn't keccak itself.
3. Compressed lookup input (should be after SecondPhase since it contains some non-linear-combination of RLC values in SecondPhase, for instance inverse of EVM word).

**Comment by CPerezz** [comment]
I don't think there's too much info about the Challenge API aside from the PR where it was merged to our halo2 fork which includes an example of usage. See: https://github.com/privacy-scaling-explorations/halo2/pull/97

In summary, in order to lookup values between circuits or, lookup 256-bit values (bigger than the field) we need to encode these values as something that fits inside a field element `Fr`. To do so, we could hash the 256-bit value. But hashing has a  prohibitive cost and wouldn't be feasible.
```
So why not RLC the byte-repr of the value? Eg:
Value: 0x5555.......77ff -> val_bytes = [u8;32]
```
Now, we do: `RLC  = v[0] * R + v[1] * R^2 + .... + v[31] * R^32`. This is therefore a value that fits inside `Fr` as all the bytes and the `R` are elements of `Fr`. 

So that's what the RLC is.

Now that we know that, what do we need to refactor? 
Well, the Challenge API was introduced after the circuits were coded. Therefore, there are some circuits that have "mock" randomness. The job is to replace these by the actual `Challenge<T>` structs removing any mock randomness left aside.

You can see examples on how to do this in these PRs:
- https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/925
- https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/965
- https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/885
- https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/770

**Comment by rrzhang139** [comment]
@CPerezz Hey! Yeah I am interested in trying this out. A few questions before I get started:

1. What do the phases mean in challenge API? Why is making challenges useful after a phase significant?
2. Im trying to identify all advice cols that require randomness. What is the size of the field element? 

This should help me understand enough to the point I can start working on it! Thanks

**Comment by CPerezz** [comment]
@rrzhang139 

1. We have Phases as a way to "order" the commitments we do. As I said above, the prover in order to have a randomness that can use for the RLCs, first commits all of the witnesses that are not RLC-related. These are `Phase0/FirstPhase`.

Then, once these are commited, we can generate the random from the commitments and then, in the `Phase1/SecondPhase` we can start commiting the RLC'd values.
We need to split in phases the commitment process as is not sound to commit together (in the same column) RLC'd and non RLC'd values.

Also, notice that Phases are just a way to hint to the proving system which column should be commited when. Nothing else.
>  Why is making challenges useful after a phase significant? 
Not sure I follow this one!

2. 
> Im trying to identify all advice cols that require randomness
Generally, all of the ones named "rlc" or that contain a 256-bit element will be a RLC column.

The size of the field is generic (we can swap curves with the trait system). But we are focused on Bn256. The field size, modulus etc are here: https://github.com/privacy-scaling-explorations/pairing/blob/1da2920e0e0b3de5929111e9d6193b6b4f0d99e3/src/bn256/fr.rs#L18
But I'm not sure why this is relevant at all for this issue. Please, let me know if I'm missing anything.

**Comment by rrzhang139** [comment]
@CPerezz Thanks! For #2, my thinking was because we only rlc values that don't fit inside a field element, so I was trying to find any advice columns that are larger than the field so that I would know to RLC them. Maybe I don't fully understand this yet, but I haven't understood a pattern as to what should be RLC'd and what shouldn't. Any suggestions how to investigate it?

**Comment by CPerezz** [comment]
>Maybe I don't fully understand this yet, but I haven't understood a pattern as to what should be RLC'd and what shouldn't.

@rrzhang139 AFAIK there's no way to know the length in bits of the elements you place inside columns. The only way to know is from a theoretical standpoint checking what you place where (according to the specs).

I recommend checking:
- https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/tables.md
- https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/exp-proof.md

With this you should be able to identify the RLC columns and assign them as `SecondPhase` at configure time.

**Comment by rrzhang139** [comment]
@CPerezz The only advice column I could think of needing randomness is [identifier](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/table.rs#L1162), but I also went ahead to find if any randomness existed in exp_circuit.rs, but couldn't find any. Looks like someone already forced included challenges to `[configure](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/exp_circuit.rs#L430)` and [witness assignment](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/exp_circuit.rs#L411) methods. So is it necessary to use the challenge API for exp_circuit right now?

**Comment by CPerezz** [comment]
With a quick check, looks like https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/82e6c878e6f4439eee57cdf932e0b9a1db26c138/zkevm-circuits/src/table.rs#L1116 would also need to be `Phase2`.

**Comment by rrzhang139** [comment]
@CPerezz It looks like challenges are passed in [synthesize time](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/exp_circuit.rs#L436). I could pass challenges into ExpCircuitConfig's [new](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/exp_circuit.rs#L44) function in anticipation for a randomness-related advice column in exp table. But not sure if its necessary. 

Should we close the issue?

I can also create a PR for the copy table if need be!

**Comment by CPerezz** [comment]
@rrzhang139 they're passed on [config time too](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/fc5a8b9d47dd844eb0c7e44a4e140e931422d211/zkevm-circuits/src/exp_circuit.rs#L430).

I think we can close the issue as I don't see any fields that require the challenge API as everything is done through limbs there. Would like @ChihChengLiang or @han0110 to confirm that I'm correct before closing anyway.

Also, with regards to the CopyTable. It is already ported to the challenge API. See [this](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/fc5a8b9d47dd844eb0c7e44a4e140e931422d211/zkevm-circuits/src/table.rs#L889)

**Comment by han0110** [comment]
Just checked and I think there is no challenge API refactor needed for `ExpCircuit`, so perhaps we could close this one.
