### ISSUE TITLE
bug: some fixed columns are not fixed at all

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-circuits#986]
In super circuit, copy_table.q_enable has no padding mechanism so it is not fixed in fact.

So using empty block and real block can result with different vks. **Even if proof from real block can be verified with vk from empty block, it is not sound since q_enable is almost disabled in (allmost?) all offsets..**

Another smaller problem is that evm circuit has tx_table.tag, which is also a fixed column, but in evm circuit it is not fixed (while in super circuit tx_table.tag is fixed). If we treat evm circuit as a "sub" circuit then it may be acceptable. But again, vk from evm circuit is not universal  anyway...

I remember we have encounter this problem (sveral times?) before.. So maybe better to setup a test case to ensure gen_vk(empty_block) == gen_vk(a_real_block)..

**Comment by han0110** [comment]
> But again, vk from evm circuit is not universal anyway...

I think we can update it to be fixed just by move `TxCircuit::assign_tx_table` logic to `TxTable::load`, and it shouldn't affect the testing time. Then also need to update this https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/9400c6237bd3efb9bc979b49fb0f25df7d763853/zkevm-circuits/src/evm_circuit.rs#L427-L428 to use `max_calldata` instead of `tx.call_data.len()`.

> So maybe better to setup a test case to ensure gen_vk(empty_block) == gen_vk(a_real_block)..

I think this is a really nice idea if we have this test in integration test.

**Comment by aguzmant103** [comment]
Meeting notes:
- Not only fixing but adding a new test to the code base to verify
- Concern this test will take a lot of time because it will need a real prover
- Key generation not much but supercircuit maybe yes

**Comment by CPerezz** [comment]
@han0110 I think that this wasn't a testing issue but rather an absence of padding for the `CopyCircuit`.
At least we've been with it with @ed255 and seems that we have discovered a couple of things that were missing!

Let us know what you think if you have time!

**Comment by ed255** [comment]
Maybe related to this issue (@CPerezz pointed me to it): https://github.com/privacy-scaling-explorations/zkevm-specs/pull/359 as all circuits will require a padding strategy to have constant fixed columns regardless of the input.

**Comment by CPerezz** [comment]
This won't be closed until https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1062 is merged.

**Comment by aguzmant103** [comment]
Note: the remaining circuit is exp circuit.
After working on the alternative PR we can close this PR as duplicate https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/1062

**Comment by ed255** [comment]
Haichen will check with the author of the spec PR https://github.com/privacy-scaling-explorations/zkevm-specs/pull/359 to determine when is the circuit PR is expected to be done in order to coordinate with PSE.  We would like to address this issue (non-constant fixed columns) with high priority, so if the expected date for the circuit is too far away we (PSE) can work on on the circuit in parallel while the spec PR is being done (considering that the strategy on how to resolve the Exp Circuit padding has already been discussed and won't change the circuit constraints)
